[package]
name = "scratch_agent"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.13", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
anyhow = "1"
dotenvy = "0.15"
time = { version = "0.3", features = ["formatting", "macros"] }
schemars = "1.2"
tavily = "2.1.0"
thiserror = "2.0.20"
rmcp = { version = "3", features = ["client", "macros", "transport-child-process"] }